server:
  port: 3000

application:
  title: 'orgaFiles'
  jsonAllowed: 'true'
  custom:
    css: 'css/custom'
    lib: 'lib/custom'

baseDir:
  path: '<enter your base path here>'

files:
  suffix:
    include: ''
    includeFilesWithNoSuffix: true
    acceptedSuffixes: ['jpeg', 'png']
  hidden:
    includeHiddenFiles: true